#!/usr/bin/env bash

SUPPORTED_CHAINS=(
    "33139:ApeChain"
    "42161:Arbitrum"
    "8453:Base"
    "1:Ethereum"
    "137:Polygon"
    "1329:Sei"
    "11155111:Sepolia"
    "56:BSC"
    "43114:Avalanche"
    "2741:Abstract"
    "80094:Berachain"
    "10143:MonadTestnet"
)

MAGIC_DROP_KEYSTORE="MAGIC_DROP_KEYSTORE"
MAGIC_DROP_KEYSTORE_FILE="$HOME/.foundry/keystores/$MAGIC_DROP_KEYSTORE"
export ETH_KEYSTORE_ACCOUNT=$MAGIC_DROP_KEYSTORE

ME_TRANSFER_VALIDATOR_V3="0x721C00D4FB075b22a5469e9CF2440697F729aA13"
LIMITBREAK_TRANSFER_VALIDATOR_V3="0x721C0078c2328597Ca70F5451ffF5A7B38D4E947"
LIMITBREAK_TRANSFER_VALIDATOR_V3_ABSTRACT="0x3203c3f64312AF9344e42EF8Aa45B97C9DFE4594"
LIMITBREAK_TRANSFER_VALIDATOR_V3_BERACHAIN="0x721c002b0059009a671d00ad1700c9748146cd1b"

ICREATOR_TOKEN_INTERFACE_ID="0xad0d7f6c" # type(ICreatorToken).interfaceId
TRUE_HEX="0x0000000000000000000000000000000000000000000000000000000000000001"

# Used on chains where we don't have a custom list
DEFAULT_LIST_ID="0"
MAGIC_EDEN_DEFAULT_LIST_ID="1"
# We use list 3 for Polygon because list 1 was already taken.
MAGIC_EDEN_POLYGON_LIST_ID="3"

DEFAULT_IMPL_ID="0"

get_factory_address() {
    # abstract factory address
    if [ "$chain_id" == "2741" ]; then
        echo "0x01c1C2f5271aDeA338dAfba77121Fc20B5176620"
    else # default
        echo "0x00000000bEa935F8315156894Aa4a45D3c7a0075"
    fi
}

get_registry_address() {
    # abstract registry address 
    if [ "$chain_id" == "2741" ]; then
        echo "0x17c9921D99c1Fa6d3dC992719DA1123dCb2CaedA"
    else # default
        echo "0x000000000e447e71b2EC36CD62048Dd2a1Cd0a57"
    fi
}

# The latest MagicDrop v1.0.1 implementation ID for each supported chain.
get_impl_id() {
    if [ "$token_standard" == "ERC721" ] && [ "$use_erc721c" == "true" ]; then
         echo "2" # 721C implementation ID on all chains
    else
        echo $DEFAULT_IMPL_ID
    fi
}