#!/usr/bin/env bash

SUPPORTED_CHAINS=(
    "33139:ApeChain"
    "42161:Arbitrum"
    "8453:Base"
    "1:Ethereum"
    "137:Polygon"
    "1329:Sei"
    "11155111:Sepolia"
    "56:BSC"
    "43114:Avalanche"
    "2741:Abstract"
    "80094:Berachain"
    "10143:MonadTestnet"
)

MAGIC_DROP_KEYSTORE="MAGIC_DROP_KEYSTORE"
MAGIC_DROP_KEYSTORE_FILE="$HOME/.foundry/keystores/$MAGIC_DROP_KEYSTORE"
export ETH_KEYSTORE_ACCOUNT=$MAGIC_DROP_KEYSTORE

ME_TRANSFER_VALIDATOR_V3="0x721C00D4FB075b22a5469e9CF2440697F729aA13"
LIMITBREAK_TRANSFER_VALIDATOR_V3="0x721C0078c2328597Ca70F5451ffF5A7B38D4E947"
LIMITBREAK_TRANSFER_VALIDATOR_V3_ABSTRACT="0x3203c3f64312AF9344e42EF8Aa45B97C9DFE4594"
LIMITBREAK_TRANSFER_VALIDATOR_V3_BERACHAIN="0x721c002b0059009a671d00ad1700c9748146cd1b"

ICREATOR_TOKEN_INTERFACE_ID="0xad0d7f6c" # type(ICreatorToken).interfaceId
TRUE_HEX="0x0000000000000000000000000000000000000000000000000000000000000001"

# Used on chains where we don't have a custom list
DEFAULT_LIST_ID="0"
MAGIC_EDEN_DEFAULT_LIST_ID="1"
# We use list 3 for Polygon because list 1 was already taken.
MAGIC_EDEN_POLYGON_LIST_ID="3"

DEFAULT_IMPL_ID="0"

get_factory_address() {
    # abstract factory address
    if [ "$chain_id" == "2741" ]; then
        echo "0x4a08d3F6881c4843232EFdE05baCfb5eAaB35d19"
    else # default
        echo "0x000000009e44eBa131196847C685F20Cd4b68aC4"
    fi
}

get_registry_address() {
    # abstract registry address 
    if [ "$chain_id" == "2741" ]; then
        echo "0x9b60ad31F145ec7EE3c559153bB57928B65C0F87"
    else # default
        echo "0x00000000caF1E3978e291c5Fb53FeedB957eC146"
    fi
}

# The latest MagicDrop v1.0.1 implementation ID for each supported chain.
get_impl_id() {
    if [ "$token_standard" == "ERC721" ] && [ "$use_erc721c" == "true" ]; then
        if [ "$chain_id" == "2741" ]; then
            echo "7" # ERC721C implementation ID / abstract
        elif [ "$chain_id" == "8453" ]; then
            echo "11" # base
        elif [ "$chain_id" == "1" ]; then
            echo "10" # ethereum
        elif [ "$chain_id" == "80094" ]; then
            echo "5" # berachain
        elif [ "$chain_id" == "10143"]; then
            echo "5" # monad testnet
        elif [ "$chain_id" == "43114" ]; then
            echo "6" # avalanche
        else
            echo "8" # all other chains
        fi
    else
        echo $DEFAULT_IMPL_ID
    fi
}