#!/usr/bin/env bash

set_rpc_url() {
    case $1 in
        1) RPC_URL="https://cloudflare-eth.com" ;; # Ethereum
        137) RPC_URL="https://polygon-rpc.com" ;; # Polygon
        8453) RPC_URL="https://mainnet.base.org" ;; # Base
        42161) RPC_URL="https://arb1.arbitrum.io/rpc" ;; # Arbitrum
        1329) RPC_URL="https://evm-rpc.sei-apis.com" ;; # Sei
        33139) RPC_URL="https://rpc.apechain.com/http" ;; # ApeChain
        56) RPC_URL="https://bsc-dataseed.binance.org" ;; # BSC
        43114) RPC_URL="https://api.avax.network/ext/bc/C/rpc" ;; # Avalanche
        11155111) RPC_URL="https://ethereum-sepolia-rpc.publicnode.com" ;; # Sepolia
        *) echo "Unsupported chain id"; exit 1 ;;
    esac

    export RPC_URL
}

set_etherscan_api_key() {
  case $1 in
      1) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_ETHEREUM ;;
      137) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_POLYGON ;;
      8453) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_BASE ;;
      42161) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_ARBITRUM ;;
      1329) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_SEI ;;
      33139) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_APECHAIN ;;
      56) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_BSC ;;
      43114) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_AVALANCHE ;;
      11155111) ETHERSCAN_API_KEY=$VERIFICATION_API_KEY_SEPOLIA ;;
      *) echo "Unsupported chain id"; exit 1 ;;
  esac

  export ETHERSCAN_API_KEY
}